server {
    listen 80;
    server_name buoc.site;

    location = /dangkytraihe {
        return 302 https://docs.google.com/forms/d/e/1FAIpQLSeUVLc2UtWgB81FgW2pOixmVgbXdNrOSxTqcyGwDFu-ezVvbA/viewform;
    }

    location = /dangkytraihe/ {
        return 302 https://docs.google.com/forms/d/e/1FAIpQLSeUVLc2UtWgB81FgW2pOixmVgbXdNrOSxTqcyGwDFu-ezVvbA/viewform;
    }

    location = /kehoachtraihe {
        return 302 https://docs.google.com/document/d/11sPjHJl2FHyS3w1_lRuzMdxuD3AkaoKY2nFyjrkcOC8/edit?tab=t.0;
    }

    location = /kehoachtraihe/ {
        return 302 https://docs.google.com/document/d/11sPjHJl2FHyS3w1_lRuzMdxuD3AkaoKY2nFyjrkcOC8/edit?tab=t.0;
    }

    location = /sotaytraisinh2026 {
        return 302 https://drive.google.com/file/d/16EooJZaVoRzymwXKZH8IvWfY7U0fpJZh/view?usp=sharing;
    }

    location = /sotaytraisinh2026/ {
        return 302 https://drive.google.com/file/d/16EooJZaVoRzymwXKZH8IvWfY7U0fpJZh/view?usp=sharing;
    }

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/buoc.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/buoc.site/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
